# Generated by Django 4.2.4 on 2024-01-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_routine_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='out_of_department',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='routine',
            name='session_type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'Lab'), ('tutorial', 'Tutorial'), ('lecture and tutorial', 'Lecture + Tutorial')], max_length=25),
        ),
    ]
