# Generated by Django 4.2.4 on 2023-08-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_routine_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='year',
            new_name='name',
        ),
    ]
