# Generated by Django 4.2.4 on 2023-12-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_year_year_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
    ]
