# Generated by Django 4.2.4 on 2023-12-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_subject_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
    ]
